#!/bin/sh -e

output="$1"
bootfs_size="$2"
rootfs_size="$3"
swap_size="$4"
rwfs_size="$5"
userfs_size="$6"
extra_size="$7"

totalsize=$(s6-expr ${bootfs_size} + ${rootfs_size} + ${swap_size} + ${rwfs_size} + ${userfs_size} + ${extra_size} + 4)

# prepare extlinux.conf

if s6-test ${KERNEL_GENERIC_ARCH} = x86 ; then
  consolearg="console=ttyS0,115200n8"
  if ${USE_GRAPHIC} ; then
    consolearg=
  fi
  if ${USE_VIRTIO_DISK} ; then
    bootpartition=/dev/vda1
  elif s6-test ${KERNEL_ARCH} = x86_64 ; then
    bootpartition=/dev/sda1
  elif s6-test ${KERNEL_ARCH} = arm ; then
    bootpartition=/dev/mmcblk0p1
  else
    bootpartition=/dev/hda1
  fi
  s6-cat > ${output}/rootfs/boot/extlinux.conf <<EOF
serial 0 115200
console 0
prompt 0
default linux
totaltimeout 1200
say extlinux booting
label linux
  linux /boot/vmlinuz
  append ro root=$bootpartition rootfstype=ext4 loglevel=4 $consolearg
EOF
fi

s6-rmrf "$output/disk-image.raw"
setuidgid ${NORMALUSER} dd if=/dev/zero of=$output/disk-image.raw bs=1 count=0 seek=${totalsize}M

setuidgid ${NORMALUSER} dd if=./sub/disk-image/bananapi-bpi-r2-first10M.img of$output/disk-image.raw bs=1M count=10

fdisk $output/disk-image.raw <<EOF
n
p
1
204800
+${bootfs_size}
n
p
2
237568
+${rootfs_size}M
n



+${swap_size}M
t
2
82
n



+${rwfs_size}M
n



n

+${userfs_size}M
n


a
1
w
EOF

loop=$(losetup -f)
losetup -P "$loop" "$output/disk-image.raw"

{
  mkfs.ext4 -O ^huge_file ${loop}p1
  mkfs.ext4 -O ^huge_file ${loop}p2
  mkswap ${loop}p3
  mkfs.ext4 -O ^huge_file ${loop}p4
  mkfs.ext4 -O ^huge_file ${loop}p6
  mkfs.ext4 -O ^huge_file ${loop}p7

  s6-mkdir -p "$output/tmp/rootfs" "$output/tmp/rwfs" "$output/tmp/userfs" "$output/tmp/stagingfs"
  mount -t ext4 ${loop}p1 "$output/tmp/rootfs"
  s6-hiercopy "$output/rootfs" "$output/tmp/rootfs"
  if s6-test ${KERNEL_GENERIC_ARCH} = x86 ; then
    dd if=${output}/build-build/opt/syslinux/usr/share/syslinux/mbr.bin of=${loop}
    extlinux -i "$output/tmp/rootfs/boot"
  fi
  umount -l "$output/tmp/rootfs"
  mount -t ext4 ${loop}p4 "$output/tmp/rwfs"
  s6-hiercopy "$output/rwfs" "$output/tmp/rwfs"
  umount -l "$output/tmp/rwfs"
  mount -t ext4 ${loop}p6 "$output/tmp/userfs"
  s6-hiercopy "$output/userfs" "$output/tmp/userfs"
  umount -l "$output/tmp/userfs"
  mount -t ext4 ${loop}p7 "$output/tmp/stagingfs"
  s6-hiercopy "$output/stagingfs" "$output/tmp/stagingfs"
  umount -l "$output/tmp/stagingfs"
} || { losetup -d "$loop" ; exit 1 ; }

losetup -d "$loop"
